# Site settings
language:               "en"
title:                  "JJ Crackers"
description:            "some stuff and other stuff"
google-verification:    ""

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
  - "assets/js/app.js"
  - "assets/scss/*.scss"
  - "assets/vendor/foundation-sites/"
  - "assets/vendor/jquery/"
  - "assets/vendor/motion-ui/"
  - "assets/vendor/phpmailer/**/*.html"
  - "assets/vendor/what-input/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulp"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"

# Plugins
gems:             ["jekyll-sitemap", "jekyll-paginate", "jekyll-feed"]

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

markdown:    kramdown
highlighter: rouge
lsi:         false

# Outputting
permalink:        "/blog/:year/:title/"
paginate_path:    "/blog/page:num"
paginate:         5

collections:
  projects:
    output: true
    permalink: /projects/:path/


kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style